excluded: # SwiftLint 검사에서 제외할 파일 경로
  - Pods
  - TwitterPractice/AppDelegate.swift
  - TwitterPractice/SceneDelegate.swift
line_length: 300
identifier_name:
  min_length: 2
disabled_rules: # 실행에서 제외할 룰 식별자들
    - trailing_whitespace
